name: Deploy

on:
  push:
     branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configura eclipse-temurin:17-jdk
        uses: actions/setup-java@v4
        with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven

      - name: Configura Docker Compose
        run: |
          sudo rm -f /usr/local/bin/docker-compose
          sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version    
        
      - name: Roda Docker Compose
        run: |
             docker compose build
             docker compose up -d

      - name: Deploy EC2 Conf
        env: 
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY}}
            USER: ubuntu
            HOST: 18.231.66.214
        run: |
           echo "$PRIVATE_KEY" > deploy_key.pem
           chmod 600 deploy_key.pem
           # Descobre o nome real da imagem gerada e salva no arquivo tar
           IMAGE_NAME=$(docker images --format "{{.Repository}}" | grep api | head -n 1)
           docker save -o vollmed-api.tar $IMAGE_NAME
           scp -o StrictHostKeyChecking=no -i deploy_key.pem vollmed-api.tar $USER@$HOST:/home/ubuntu/
           scp -o StrictHostKeyChecking=no -i deploy_key.pem init.sql $USER@$HOST:/home/ubuntu/
           scp -o StrictHostKeyChecking=no -i deploy_key.pem docker-compose-prod.yaml $USER@$HOST:/home/ubuntu/
           scp -o StrictHostKeyChecking=no -i deploy_key.pem script-deploy.sh $USER@$HOST:/home/ubuntu/
           ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST "chmod +x script-deploy.sh && ./script-deploy.sh"
