name: CI Voll Med

on:
  push:
     branches: ["main"]
  pull_request:
      branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configura eclipse
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configura Docker Compose
      uses: docker/setup-compose-action@v2
      with:
        version: latest 
        
    - name: Roda Docker Compose
      run: docker-compose up -d

    - name: Executa testes unitários
      run: mvn -B verify
